"""change table name

Revision ID: 486664a03527
Revises: 
Create Date: 2025-01-05 16:59:34.032243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486664a03527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('dealer', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mytable')
    # ### end Alembic commands ###
