"""change actual name

Revision ID: e0c4a93d566b
Revises: 486664a03527
Create Date: 2025-01-05 17:03:23.351332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c4a93d566b'
down_revision = '486664a03527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Video Survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('dealer', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mytable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dealer', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mytable_pkey')
    )
    op.drop_table('Video Survey')
    # ### end Alembic commands ###
